import os
import streamlit as st
import pandas as pd
from io import BytesIO
from theme import load_data
from fpdf import FPDF
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

st.markdown("<h1>💾 Download Center</h1>", unsafe_allow_html=True)
st.markdown("<p style='color: #64748b; font-size: 14px;'>Export database tables and compiled reporting assets locally in multiple formats.</p>", unsafe_allow_html=True)

df = load_data()

if df.empty:
    st.warning("⚠️ No data available in database. Run the ETL pipeline first.")
else:
    # Compile download byte blocks
    csv_buffer = BytesIO()
    df.to_csv(csv_buffer, index=False)
    csv_bytes = csv_buffer.getvalue()
    
    excel_buffer = BytesIO()
    with pd.ExcelWriter(excel_buffer, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name="Transformed Student Data")
    excel_bytes = excel_buffer.getvalue()
    
    # PDF compiler function
    def compile_pdf(dataframe):
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 16)
        pdf.set_text_color(30, 58, 138)
        pdf.cell(0, 10, "Student Performance Analytics Report", 0, 1, "C")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(0, 8, "GENERATED BY EDUANALYTICS ETL VIZ.PY", 0, 1, "C")
        pdf.ln(10)
        
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(0, 8, "1. Executive Summary", 0, 1)
        pdf.set_font("Helvetica", "", 10)
        
        total = len(dataframe)
        avg = round(dataframe["average_marks"].mean(), 2)
        pass_pct = round((dataframe["result"] == "Pass").sum() / total * 100, 2)
        
        pdf.cell(0, 6, f"Total Students: {total}", 0, 1)
        pdf.cell(0, 6, f"Average Marks: {avg}%", 0, 1)
        pdf.cell(0, 6, f"Pass Percentage: {pass_pct}%", 0, 1)
        pdf.ln(10)
        
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 8, "2. Top Performers Summary", 0, 1)
        pdf.ln(2)
        
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(20, 8, "ID", 1, 0, "C")
        pdf.cell(45, 8, "Name", 1, 0, "L")
        pdf.cell(20, 8, "Branch", 1, 0, "C")
        pdf.cell(25, 8, "Final Marks", 1, 0, "C")
        pdf.cell(25, 8, "Attendance", 1, 0, "C")
        pdf.cell(20, 8, "Grade", 1, 1, "C")
        
        top_10 = dataframe.sort_values(by="average_marks", ascending=False).head(10)
        pdf.set_font("Helvetica", "", 9)
        
        for idx, row in top_10.iterrows():
            pdf.cell(20, 7, str(row["studentid"]), 1, 0, "C")
            pdf.cell(45, 7, str(row["name"]), 1, 0, "L")
            pdf.cell(20, 7, str(row["department"]), 1, 0, "C")
            pdf.cell(25, 7, f"{row['finalmarks']:.1f}", 1, 0, "C")
            pdf.cell(25, 7, f"{row['attendance']:.1f}%", 1, 0, "C")
            pdf.cell(20, 7, str(row["grade"]), 1, 1, "C")
            
        return pdf.output()
        
    pdf_bytes = bytes(compile_pdf(df))
    
    col_d1, col_d2 = st.columns(2)
    
    with col_d1:
        st.markdown("""
            <div style="background-color:rgba(128,128,128,0.05); padding:15px; border-radius:10px; border:1px solid rgba(128,128,128,0.1); margin-bottom:15px;">
                <h4>Relational Relational Tables</h4>
                <p style="font-size:12px; color:#64748b;">Download raw student performance records as cleaned datasets for local analysis.</p>
            </div>
        """, unsafe_allow_html=True)
        st.download_button(
            label="⬇️ Download CSV File",
            data=csv_bytes,
            file_name="student_records_cleaned.csv",
            mime="text/csv",
            use_container_width=True
        )
        st.write("")
        st.download_button(
            label="⬇️ Download Excel Sheet (.xlsx)",
            data=excel_bytes,
            file_name="student_records_cleaned.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            use_container_width=True
        )
        
    with col_d2:
        st.markdown("""
            <div style="background-color:rgba(128,128,128,0.05); padding:15px; border-radius:10px; border:1px solid rgba(128,128,128,0.1); margin-bottom:15px;">
                <h4>Summary Reports & Graphics</h4>
                <p style="font-size:12px; color:#64748b;">Download compiled report layouts and charts matching external sync nodes.</p>
            </div>
        """, unsafe_allow_html=True)
        st.download_button(
            label="⬇️ Download PDF Document",
            data=pdf_bytes,
            file_name="student_analytics_report.pdf",
            mime="application/pdf",
            use_container_width=True
        )
        st.write("")
        
        # Read local html report
        html_report_path = "reports/report.html"
        html_report_bytes = b"No HTML report available. Run pipeline."
        if os.path.exists(html_report_path):
            with open(html_report_path, "rb") as f:
                html_report_bytes = f.read()
                
        st.download_button(
            label="⬇️ Download static HTML Report",
            data=html_report_bytes,
            file_name="report.html",
            mime="text/html",
            use_container_width=True
        )
        
    # Render static summary png
    st.markdown("---")
    st.subheader("Static Visual Summary (summary.png)")
    png_path = "reports/summary.png"
    if os.path.exists(png_path):
        st.image(png_path, caption="Static analytics chart attached to email reports.")
        with open(png_path, "rb") as f:
            png_bytes = f.read()
        st.download_button(
            label="⬇️ Download summary.png Image",
            data=png_bytes,
            file_name="summary.png",
            mime="image/png"
        )
    else:
        st.info("No static summary graphic found. Run the ETL pipeline to generate.")
